# Site settings
title: The Open Show
email: your-email@domain.com
url: https://github.com/timmmmyboy/connectedlearning.tools
description: "Presentation support information for DML 2015 session on tool and strategies for open connected learning"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a> This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
  location: DML 2015
  social: Socially Yours
  credits: Show Stars

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://www.twitter.com/dmlconference
  - title: facebook
    url: https://www.facebook.com/DMLResearchHub
  - title: google-plus
    url: https://plus.google.com/u/0/communities/113655426574061601680
  - title: flickr
    url: http://www.flickr.com/photos/dmlcentral/
  - title: github
    url: https://github.com/timmmmyboy/connectedlearning.tools


# Postal address (add as many lines as necessary)
address:
  - line: Equity by Design
  - line: <a href="http://dml2015.dmlhub.net/">dml2015.dmlhub.net</a>
  - line: Los Angeles, CA

# Credits content
credits: '<ul><li><a href="mailto:cogdogblog@gmail.com">Alan Levine</a>, Edtech Consultant</li>
<li><a href="mailto:laurakgibbs@gmail.com">Laura Gibbs</a>, University of Oklahoma</li>
<li><a href="mailto:tim@reclaimhosting.com">Tim Owens</a>, <a href="https://reclaimhosting.com">Reclaim Hosting</a></li>
<li><a href="mailto:jimgroom@gmail.com">Jim Groom</a>, University of Mary Washington</li>
<li><a href="mailto:erin@withknown.com">Erin Richey</a>, <a href="http://withknown.com">Known</a></li>
<li><a href="mailto:ben@withknown.com">Ben Werdmuller</a>, <a href="http://withknown.com">Known</a></li>
<li><a href="mailto:jdubbyah@gmail.com">Jonathan Worth</a>, phonar</li></ul>'

# Build settings
markdown: kramdown
permalink: pretty
