# Site settings
title: The Open Show
email: your-email@domain.com
url: https://github.com/timmmmyboy/connectedlearning.tools
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/timmmmyboy/connectedlearning.tools

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: '<ul><li><a href="mailto:cogdogblog@gmail.com">Alan Levine</a>, Edtech Consultant</li>
<li><a href="mailto:laurakgibbs@gmail.com">Laura Gibbs</a>, University of Oklahoma</li>
<li><a href="mailto:tim@reclaimhosting.com">Tim Owens</a>, <a href="https://reclaimhosting.com">Reclaim Hosting</a></li>
<li><a href="mailto:jimgroom@gmail.com">Jim Groom</a>, University of Mary Washington</li>
<li><a href="mailto:erin@withknown.com">Erin Richey</a>, <a href="http://withknown.com">Known</a></li>
<li><a href="mailto:ben@withknown.com">Ben Werdmuller</a>, <a href="http://withknown.com">Known</a></li>
<li><a href="mailto:jdubbyah@gmail.com">Jonathan Worth</a>, phonar</li></ul>'

# Build settings
markdown: kramdown
permalink: pretty
