# Site settings
title: The Open Show
email: cogdogblog@gmail.com
url: https://github.com/timmmmyboy/connectedlearning.tools
description: "Presentation support information for DML 2015 session on tool and strategies for open connected learning"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  link: BC3DF0 #BC3DF0

# Footer settings
footer:
  copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a> Unless otherwise noted, everything is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
  location: DML 2015
  social: DML Socially
  credits: Show Stars
  sitenotes: This site is powered by <a href="http://jekyllrb.com/" target="_blank">Jekykll</a>, hosted for free by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>, and design based on  <a href="http://jekyllthemes.org/themes/freelancer/" target="_blank">Freelancer Theme</a> with mods by <a href="http://cogdog.info" target="_blank">@cogdog</a>. <a href="http://flickr.com/photos/drewmaughan/9637596345" target="_blank">Mia's Talk Show</a> flickr image by shared under a Creative Commons (BY-NC-SA) license. And we sure appreciate the perfect domain provided by <a href="http://reclaimhosting.com" target="_blank">Reclaim Hosting</a>!

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://www.twitter.com/dmlconference
  - title: facebook
    url: https://www.facebook.com/DMLResearchHub
  - title: google-plus
    url: https://plus.google.com/u/0/communities/113655426574061601680
  - title: flickr
    url: http://www.flickr.com/photos/dmlcentral/
  - title: github
    url: https://github.com/timmmmyboy/connectedlearning.tools


# Postal address (add as many lines as necessary)
address:
  - line: Equity by Design
  - line: <a href="http://dml2015.dmlhub.net/">dml2015.dmlhub.net</a>
  - line: Los Angeles, CA

# Credits content
credits: '<a href="http://cogdog.info/">Alan Levine</a> &bull; <a href="http://cogdogblog.com">CogDogBlog</a><br /><a href="http://mythfolklore.net/">Laura Gibbs</a> &bull; <a href="http://www.ou.edu">University of Oklahoma</a><br /><a href="http://timowens.io/">Tim Owens</a> &bull; <a href="https://reclaimhosting.com">Reclaim Hosting</a><br /><a href="http://bavatuesdays.com">Jim Groom</a> &bull;  <a href="https://reclaimhosting.com">Reclaim Hosting</a><br /><a href="http://erinjorichey.com">Erin Richey</a> &bull;  <a href="http://withknown.com">Known</a><br /><a href="http://werd.io">Ben Werdmuller</a> &bull;  <a href="http://withknown.com">Known</a><br /><a href="https://about.me/jonathan_worth">Jonathan Worth</a> &bull;  <a href="http://phonar.com/">phonar</a>'

# Build settings
markdown: kramdown
permalink: pretty
